sudo: required
language: generic

services:
  - docker
env:
        global:
                - SHA=$(git rev-parse HEAD)
                - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
        - openssl aes-256-cbc -K $encrypted_a3386c1dbbae_key -iv $encrypted_a3386c1dbbae_iv -in multi-k8s-314112-05cdc0f3930d.json.enc -out multi-k8s-314112-05cdc0f3930d.json -d
        - curl https://sdk.cloud.google.com | bash > /dev/null;
        - source $HOME/google-cloud-sdk/path.bash.inc
        - gcloud components update kubectl
        - gcloud auth activate-service-account --key-file multi-k8s-314112-05cdc0f3930d.json
        - gcould config set project multi-k8s-314112
        - gcloud config set compute/zone asia-south1-a
        - gcloud container clusters get-credentials multi-cluster
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t cygnetops/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cygnetops/react-test npm test

deploy:
        provider: script
        script: bash ./deploy.sh
        on:
                branch: master
